config/routes.rb
SpecialServer::Application.routes.draw do

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :users do
      member do
        get :following, :followers
      end
      collection do
        get 'page/:page', action: :index
        get :search
      end
    end
    resources :sessions,        only: [:new, :create, :destroy]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts,      only: [:create, :destroy] do
      collection do
        get :search
      end
    end
    resources :relationships,   only: [:create, :destroy]

    get '/signup',         to: 'users#new'
    get '/activation/:id', to: 'activations#update', as: :activation
    get '/signin',         to: 'sessions#new'
    delete '/signout',     to: 'sessions#destroy'

    get '/help',    to: 'static_pages#help'
    get '/about',   to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'

    root to: "static_pages#home", via: :get
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        member do
          get :following, :followers, :microposts
        end
      end
      resources :authentication, only: :create
      resources :password_resets, only: [:create, :update]
      resources :microposts,     only: [:create, :destroy]
      resources :relationships,  only: [:create, :destroy]
      get  '/feed',   to: 'users#feed'
      post '/signin', to: 'authentication#create'
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  password_digest        :string(255)
#  remember_token         :string(255)
#  admin                  :boolean          default(FALSE)
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  activation_token       :string(255)
#  activation_sent_at     :datetime
#  active                 :boolean          default(FALSE)
#  nick                   :string(255)      not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :nick, :email, :password, :password_confirmation
  has_secure_password
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id",
                           dependent: :destroy
  has_many :followed_users, through: :relationships,
                            source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships,
                       source: :follower

  before_save :create_remember_token

  scope :admins, where(admin: true)
  scope :active, where(active: true)

  NAME_MAX_LEN = 50
  validates :name, presence: true,
                   length: { maximum: NAME_MAX_LEN }

  NICK_MIN_LEN = 2
  NICK_MAX_LEN = 30
  NICK_REGEX = /\A[\w\p{Han}\-]+\z/i
  validates :nick, presence: true,
                   length: { minimum: NICK_MIN_LEN, maximum: NICK_MAX_LEN},
                   format: NICK_REGEX,
                   uniqueness: true


  include EmailValidations
  validates :email, uniqueness: { case_sensitive: false }

  include PasswordValidations

  include Tire::Model::Search
  include Tire::Model::Callbacks

  index_name "#{Tire::Model::Search.index_prefix}_users"

  tire.mapping do
    indexes :id, type: 'integer'
    indexes :name
    indexes :email
    indexes :nick
  end

  def self.search(params)
    tire.search(load: true, page: params[:page]||1) do
      query { string params[:query] } if params[:query].present?
      sort  { by :id } if params[:query].blank? # as returned by database
    end
  end

  def self.find_by_email_or_nick(string)
    self.where('email = :val OR nick = :val', val: string).first
  end

  def feed
    Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  def send_password_reset
    token_for :password_reset_token, :password_reset_sent_at
    save! validate: false
    UserMailer.password_reset(self).deliver
  end

  def send_activation
    token_for :activation_token, :activation_sent_at
    save! validate: false
    UserMailer.activation(self).deliver
  end

  def activate!
    self.active = true
    clear_token :activation_token, :activation_sent_at
    save! validate: false
  end

  def active?
    self.active
  end

  def clear_password_token!
    clear_token :password_reset_token, :password_reset_sent_at
    save! validate: false
  end

private

  def create_remember_token
    token_for :remember_token, nil
  end

  def token_for(token_field, sent_field)
    self[token_field] = SecureRandom.urlsafe_base64
    self[sent_field] = Time.zone.now if sent_field
  end

  def clear_token(token_field, sent_field)
    self[token_field] = nil
    self[sent_field] = nil
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  include Api::V1::UsersHelper, Api::V1::MicropostsHelper

  before_filter :find_user, only: [:show, :following, :followers, :microposts]

  #TODO: https://github.com/fabrik42/acts_as_api

  def index
    users = User.page(page) 
    respond_with api_user_list(users)
  end

  def show
    respond_with api_user(@user)
  end

  def following
    followed_users = @user.followed_users.page(page)
    respond_with api_user_list(followed_users)
  end

  def followers
    followers = @user.followers.page(page)
    respond_with api_user_list(followers)
  end

  def microposts
    microposts = @user.microposts.page(page)
    respond_with microposts
  end

  def feed
    feeds = Micropost.from_users_followed_by(@current_user).page(page)
    respond_with api_feed_list(feeds)
  end

private

  def find_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    error = { error: I18n.t('not_found', name: I18n.t('user')) }
    respond_with error, status: :not_found
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include ApplicationHelper

  before_filter :protect, :only => :index

  def index
    @title = "User Hub"
    # this will be a protected page for viewing user information
  end
  
  def login
    @title = "Login"
    if param_posted?(:user)
      @user = User.new(params[:user])
      user = User.find_by_screen_name_and_password(@user.screen_name, @user.password)
      if user
        user.login!(session)
        flash[:notice] = "User #{user.screen_name} logged in!"
        redirect_to_forwarding_url
      else
        @user.clear_password!
        flash[:notice] = "Invalid screen name/password combination"
      end
    end
  end

  def logout
    User.logout!(session)
    flash[:notice] = "Logged out"
    redirect_to :action => "index", :controller => "site"
  end

  def register
    @title = "Register"
    if param_posted?(:user)
      @user = User.new(params[:user])
      if @user.save
        @user.login!(session)
        flash[:notice] = "User #{@user.screen_name} created!"
        redirect_to_forwarding_url
      else
        # should not necessary because HTML input password does not keep the value
        @user.clear_password!
      end
    end
  end

  def protected
    unless logged_in?
      session[:protected_page] = request.request_uri
      flash[:notice] = "Please log in first"
      redirect_to :action => "login"
      return false
    end
  end

private
  
  # Protect a page from unauthorize acces.
  def protect 
    unless logged_in?
      redirect_to :action => "login"
      flash[:notice] = "Please log in first"
      return false
    end
  end

  # Return true if a parameter corresponding to the given symbol was posted.
  def param_posted?(symbol)
    request.post? and params[symbol]
  end

  # Redirect to the previously request URL (if present)
  def redirect_to_forwarding_url
    if (redirect_url = session[:protected_page])
      session[:protected_page] = nil
      redirect_to redirect_url
    else
      redirect_to :action => "index"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,
                only: [:index, :edit, :update, :following, :followers]
  before_filter :correct_user,           only: [:edit, :update]
  before_filter :already_signed_in_user, only: [:new, :create]
  before_filter :admin_user,             only: :destroy
  before_filter :self_delete,            only: :destroy

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      @user.send_activation
      flash[:success] = I18n.t('users.create.success', email: @user.email)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def confirm
    @user = User.find_by_activation_token! params[:id]
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = I18n.t('users.update.success')
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.page(params[:page])
  end

  def search
    begin
      @users = User.search params
    rescue Tire::Search::SearchRequestFailed
      # fail silently in case of errors
      @users = []
      error = true
    end
    flash[:message] = I18n.t('users.search.not_found') if @users.empty? or error
    render :index
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.page(params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = I18n.t('users.destroy.success')
    redirect_to users_path
  end

  def following
    @title = I18n.t('users.following.title')
    @user = User.find(params[:id])
    @users = @user.followed_users.page(params[:page])
    render 'show_follow'
  end

  def followers
    @title = I18n.t('users.followers.title')
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page])
    render 'show_follow'
  end

private

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def already_signed_in_user
    redirect_to(root_path) if signed_in?
  end

  def self_delete
    user = User.find(params[:id])
    redirect_to(root_path) if current_user?(user)
  end

end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
  
  def api_user(user)
    { id: user.id, email: user.email, name: user.name }
  end

  def api_user_list(users)
    users.map! { |u| api_user(u) }
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    if Rails.env.development? or Rails.env.test?
      gravatar_url = "gravatar-#{size}.png"
    else
      gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    end
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  # Return '@nickname' for the given user
  def at_nick(user)
    "@#{user.nick}"
  end

end

app/views/users/_fields.html.haml
= f.label :name, t('.name')
= f.text_field :name

= f.label :email, t('.email')
= f.text_field :email

= f.label :nick, t('.nick')
= f.text_field :nick
-# TODO autofill nick with js

= f.label :password, t('.password')
= f.password_field :password

= f.label :password_confirmation, t('.confirmation')
= f.password_field :password_confirmation

app/views/users/_follow.html.haml
= form_for current_user.relationships.build(followed_id: @user.id),
           remote: true do |f|
  %div= f.hidden_field :followed_id
  = f.submit t('.button'), class: 'btn btn-large btn-primary'

app/views/users/_follow_form.html.haml
- unless current_user? @user
  #follow_form
    - if current_user.following? @user
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_unfollow.html.haml
= form_for current_user.relationships.find_by_followed_id(@user.id),
           html: { method: :delete },
           remote: true do |f|
  %div= f.hidden_field :followed_id
  = f.submit t('.button'), class: 'btn btn-large'

app/views/users/_user.html.haml
%li
  = gravatar_for user, size: 52
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    = link_to t('users.delete.button'), user, method: :delete,
              confirm: t('users.delete.confirm'),
              class: 'btn btn-mini btn-danger pull-right'
  .nick= at_nick user

app/views/users/_users.html.haml
= will_paginate

%ul.users
  = render @users

= will_paginate

app/views/users/edit.html.haml
- provide :title, t('.title')
%h1= t('.title')
.row
  .span6.offset3
    = form_for(@user) do |f|
      = render 'shared/error_messages', object: f.object
      = render 'fields', f: f
      = f.submit t('.button'), class: 'btn btn-large btn-primary'
    = gravatar_for(@user)
    %a(href="http://gravatar.com/emails" target="_blank")
      = t('.change_avatar')

app/views/users/index.html.haml
- provide :title, t('.title')
%h1= t('.title')

.row.top-nav
  .pull-left
    = paginate @users unless @users.empty?
  .pull-right.span4
    = form_tag search_users_path, method: :get, class: 'form-search' do
      = text_field_tag :query, params[:query], class: 'input-medium search-query'
      = submit_tag t('.search'), name: nil, class: 'btn'

%ul.users
  = render @users

= paginate @users unless @users.empty?

app/views/users/index.js.erb
$('.users').html('<%= j render(@users) %>');
$('.pagination').html('<%= j paginate @users, remote: true %>');
$('html, body').animate({ scrollTop: 0 }, 'slow');
$('.alert').remove();

app/views/users/new.html.haml
- provide :title, t('.title')
%h1= t('.title')

.row
  .span6.offset3
    = form_for(@user) do |f|
      = render 'shared/error_messages', object: f.object
      = render 'fields', f: f
      = f.submit t('.button'), class: 'btn btn-large btn-primary'

app/views/users/show.html.haml
- provide :title, @user.name
.row
  %aside.span4
    %section
      %h1
        = gravatar_for @user
        = @user.name
      %span.nick= at_nick @user
    %section
      = render 'shared/stats'
  .span8
    = render 'follow_form' if signed_in?
    - if @user.microposts.any?
      %h3 #{t('users.show.microposts')} (#{@user.microposts.count})
      %ol.microposts
        = render @microposts
      = paginate @microposts

app/views/users/show.js.erb
$('.microposts').html('<%= j render @microposts %>');
$('.pagination').html('<%= j paginate @microposts, remote: true %>');
$('html, body').animate({ scrollTop: 0 }, 'slow');

app/views/users/show_follow.html.haml
.row
  %aside.span4
    %section
      = gravatar_for @user
      %h1= @user.name
      %span= link_to t('users.show.profile'), @user
      %span
        %strong #{t('users.show.microposts')}:
        = @user.microposts.count
    %section
      = render 'shared/stats'
      - unless @users.empty?
        .user_avatars
          - @users.each do |user|
            = link_to gravatar_for(user, size: 30), user
  .span8
    %h3= yield(:title)
    - if @users.any?
      %ul.users
        = render @users
      = paginate @users

app/views/users/show_follow.js.erb
$('.users').html('<%= j render @users %>');
$('.pagination').html('<%= j paginate @users, remote: true %>');
$('html, body').animate({ scrollTop: 0 }, 'slow');