config/routes.rb
SpecialServer::Application.routes.draw do

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :users do
      member do
        get :following, :followers
      end
      collection do
        get 'page/:page', action: :index
        get :search
      end
    end
    resources :sessions,        only: [:new, :create, :destroy]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts,      only: [:create, :destroy] do
      collection do
        get :search
      end
    end
    resources :relationships,   only: [:create, :destroy]

    get '/signup',         to: 'users#new'
    get '/activation/:id', to: 'activations#update', as: :activation
    get '/signin',         to: 'sessions#new'
    delete '/signout',     to: 'sessions#destroy'

    get '/help',    to: 'static_pages#help'
    get '/about',   to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'

    root to: "static_pages#home", via: :get
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        member do
          get :following, :followers, :microposts
        end
      end
      resources :authentication, only: :create
      resources :password_resets, only: [:create, :update]
      resources :microposts,     only: [:create, :destroy]
      resources :relationships,  only: [:create, :destroy]
      get  '/feed',   to: 'users#feed'
      post '/signin', to: 'authentication#create'
    end
  end

end

app/views/layouts/_development_info.html.haml
= debug params
= debug request.flash
= debug request.server_software

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    = t('.application_by')
    %a(href="mailto:paolo.dapice@gmail.com?subject=Sample Application") Paolo D'Apice
  %nav
    %ul
      %li= link_to t('static_pages.about.title'),   about_path
      %li= link_to t('static_pages.contact.title'), contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to(root_path, id: 'logo') do
        = logo + '  ' + t('appname')
        %span.label.label-important beta
      %nav
        %ul.nav.pull-right
          = render 'layouts/locale_switcher'
          = render 'layouts/mailcatcher' if Rails.env.development?
          %li= link_to t('static_pages.home.title'), root_path
          %li= link_to t('static_pages.help.title'), help_path
          - if signed_in?
            %li= link_to t('users.index.title'), users_path
            %li= link_to t('microposts.search.title-short'), search_microposts_path
            %li#fat-menu.dropdown
              %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
                = current_user.email
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to(current_user) do
                    %i.icon-user
                    = t('.profile')
                %li
                  = link_to(edit_user_path(current_user)) do
                    %i.icon-cog
                    = t('.settings')
                %li.divider
                %li
                  = link_to(signout_path, method: :delete) do
                    %i.icon-off
                    = t('.signout')
          - else
            %li= link_to t('.signin'), signin_path

app/views/layouts/_locale_switcher.html.haml
%li#fat-menu.dropdown
  %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
    = flag I18n.locale
    %b.caret
  %ul.dropdown-menu
    - I18n.available_locales.each do |locale|
      %li= link_to flag(locale) + '  ' + I18n.name_for_locale(locale), locale: locale

app/views/layouts/_mailcatcher.html.haml
%li
  = link_to('http://localhost:1080', target: '_blank') do
    %i.icon-envelope.icon-white

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script(src="http://html5shiv.googlecode.com/svn/trunk/html5.js")

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title yield(:title)
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield :head
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        = content_tag :div, value, class: "alert alert-#{key}"
      = yield
      = render 'layouts/footer'
      = render 'layouts/development_info' if Rails.env.development?

app/views/layouts/user_mailer.html.haml
!!! Strict
%html(xmlns="http://www.w3.org/1999/xhtml")
  %head
    %meta(content="text/html; charset=utf-8" http-equiv="Content-Type")/
    %meta(content="width=device-width, initial-scale=1.0" name="viewport")/
    -# TODO move to separate css file
    :css
      /* Based on The MailChimp Reset INLINE: Yes. */
      /* Client-specific Styles */
      #outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
      body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
      /* Prevent Webkit and Windows Mobile platforms from changing default font sizes.*/
      .ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */
      .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
      /* Forces Hotmail to display normal line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */
      #backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
      /* End reset */

      /* Some sensible defaults for images
      Bring inline: Yes. */
      img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;}
      a img {border:none;} 
      .image_fix {display:block;}

      /* Yahoo paragraph fix
      Bring inline: Yes. */
      p {margin: 1em 0;}

      /* Hotmail header color reset
      Bring inline: Yes. */
      h1, h2, h3, h4, h5, h6 {color: black !important;}

      h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}

      h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {
      color: red !important; /* Preferably not the same color as the normal header link color.  There is limited support for psuedo classes in email clients, this was added just for good measure. */
      }

      h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {
      color: purple !important; /* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. */
      }

      /* Outlook 07, 10 Padding issue fix
      Bring inline: No.*/
      table td {border-collapse: collapse;}

      /* Remove spacing around Outlook 07, 10 tables
      Bring inline: Yes */
      table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }

      /* Styling your links has become much simpler with the new Yahoo.  In fact, it falls in line with the main credo of styling in email and make sure to bring your styles inline.  Your link colors will be uniform across clients when brought inline.
      Bring inline: Yes. */
      a {color: orange;}

      /* MOBILE TARGETING */
      @media only screen and (max-device-width: 480px) {
        /* Part one of controlling phone number linking for mobile. */
        a[href^="tel"], a[href^="sms"] {
          text-decoration: none;
          color: blue; /* or whatever your want */
          pointer-events: none;
          cursor: default;
        }

        .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
          text-decoration: default;
          color: orange !important;
          pointer-events: auto;
          cursor: default;
        }
      }

      /* More Specific Targeting */

      @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
        /* You guessed it, ipad (tablets, smaller screens, etc) */
        /* repeating for the ipad */
        a[href^="tel"], a[href^="sms"] {
          text-decoration: none;
          color: blue; /* or whatever your want */
          pointer-events: none;
          cursor: default;
        }

        .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
          text-decoration: default;
          color: orange !important;
          pointer-events: auto;
          cursor: default;
        }
      }

      @media only screen and (-webkit-min-device-pixel-ratio: 2) {
      /* Put your iPhone 4g styles in here */
      }

      /* Android targeting */
      @media only screen and (-webkit-device-pixel-ratio:.75){
      /* Put CSS for low density (ldpi) Android layouts in here */
      }
      @media only screen and (-webkit-device-pixel-ratio:1){
      /* Put CSS for medium density (mdpi) Android layouts in here */
      }
      @media only screen and (-webkit-device-pixel-ratio:1.5){
      /* Put CSS for high density (hdpi) Android layouts in here */
      }
      /* end Android targeting */
    / Targeting Windows Mobile
    /[if IEMobile 7]
      <style type="text/css">

      </style>
    /* END MOBILE TARGETING */
    /[if gte mso 9]
      <style>
      \/* Target Outlook 2007 and 2010 */
      </style>
  %body
    %table#backgroundTable(border="0" cellpadding="0" cellspacing="0")
      %tr
        %td(valign="top")
          %table(align="center" border="0" cellpadding="0" cellspacing="0")
            %tr
              %td
                = yield :title
            %tr
              %td
                %h2 #{@user.name},
            %tr
              %td
                = yield
            %tr
              %td(align="right")
                = link_to t('appname'), root_url, target: '_blank',
                                        style: "color: orange; text-decoration: none;"